cc_binary(
    name = "mlmd_bench",
    srcs = ["mlmd_bench.cc"],
    deps = [
    	"//ml_metadata/proto:metadata_bench_proto",
    	"//ml_metadata/proto:metadata_store_proto",
    	"//ml_metadata/metadata_store:metadata_store",
    	"//ml_metadata/metadata_store:metadata_store_factory",
    	"@com_google_protobuf//:protobuf",
    ]
)